export const VERSICULOS = [
    { texto: "Posso todas as coisas naquele que me fortalece.", referencia: "Filipenses 4:13" },
    { texto: "Porque para Deus nada é impossível.", referencia: "Lucas 1:37" },
    { texto: "O Senhor é o meu pastor; nada me faltará.", referencia: "Salmos 23:1" },
    { texto: "Espera no Senhor, anima-te, e ele fortalecerá o teu coração.", referencia: "Salmos 27:14" },
    { texto: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.", referencia: "Isaías 41:10" },
    { texto: "Tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor.", referencia: "Colossenses 3:23" },
    { texto: "Orai sem cessar.", referencia: "1 Tessalonicenses 5:17" },
    { texto: "E conhecereis a verdade, e a verdade vos libertará.", referencia: "João 8:32" },
    { texto: "Porque tudo o que é nascido de Deus vence o mundo.", referencia: "1 João 5:4" },
    { texto: "Sede fortes e corajosos. Não temais, nem vos espanteis.", referencia: "Deuteronômio 31:6" },
    { texto: "Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.", referencia: "Salmos 37:5" },
    { texto: "O choro pode durar uma noite, mas a alegria vem pela manhã.", referencia: "Salmos 30:5" },
    { texto: "Alegrai-vos sempre no Senhor; outra vez digo: alegrai-vos.", referencia: "Filipenses 4:4" },
    { texto: "Porque onde estiverem dois ou três reunidos em meu nome, ali estou eu no meio deles.", referencia: "Mateus 18:20" },
    { texto: "Buscai primeiro o reino de Deus e a sua justiça, e todas essas coisas vos serão acrescentadas.", referencia: "Mateus 6:33" },
    { texto: "Peça, e dar-se-vos-á; buscai, e encontrareis; batei, e abrir-se-vos-á.", referencia: "Mateus 7:7" },
    { texto: "Grandes coisas fez o Senhor por nós; por isso estamos alegres.", referencia: "Salmos 126:3" },
    { texto: "Perto está o Senhor dos que têm o coração quebrantado.", referencia: "Salmos 34:18" },
    { texto: "Em paz também me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança.", referencia: "Salmos 4:8" },
    { texto: "Fiel é Deus, pelo qual fostes chamados para a comunhão de seu Filho.", referencia: "1 Coríntios 1:9" },
];